### PR TITLE
added optional paste and copy hook-ins, made the css inline

### PR DESCRIPTION
**Pull request by tnrich**
Hey @WickyNilliams, I realized while using your excellent clipboard component, that it would be nice to be able to hook into the onCopy and onPaste events of the textarea/input field so I added the option of doing that. In the same stroke, I also inlined the css because I don't think the majority of people would want to have to add the css manually when it works just as well being inlined (maybe a small percentage of people would be against that because of a slightly larger file size if they use this component MANY times).

An example of how this would be used can be found in test.js:

```
var Clipboard = require("./index.js");
var React = require("react");

var App = React.createClass({

    handlePaste: function(event) {
        console.log('paste!');
        if (event.clipboardData.items[0]) {
            event.clipboardData.items[0].getAsString(function(string) {
                console.log('Pasted: ', string)
            });
        }
    },

    handleCopy: function(event) {
        console.log('copy!');
        //perform necessary copy logic
    },

    render: function() {
        var text = JSON.stringify(this.props.data, null, "  ");
        return (
          <div>
            <p>Press Cmd + C to copy:</p>
            <pre>{text}</pre>
            <Clipboard 
                value={text}
                onPaste={this.handlePaste}
                onCopy={this.handleCopy}
            />
          </div>
        );
    }
});

var data = { foo : 1, bar : 2 };
React.render(<App data={data} />, document.body);
```

To test it I set up a little webpack config which can be run by:

```
sudo npm install webpack -g
sudo npm install webpack-dev-server -g 
webpack-dev-server
```

You can then view the test script running in the browser at:
http://localhost:8080/webpack-dev-server/

Check it out. I'm happy to add/remove things to fit your liking. 

Thanks! 
Thomas

### CODE REVIEW

**Comment by tnrich** [comment]
Oh, and you'll have to open the console to see the onCopy/onPaste events being fired.

**Comment by WickyNilliams** [comment]
Thanks for the PR.

My only concern is that there are a lot of changes/additions bundled into one commit and one PR. Ideally each of them should be separate PRs. So let's discuss each in isolation:

**Events**: You've added copy and paste events. First thought: why the paste event? The component only deals with copying, so paste is not really of any use. So we should drop that unless you have a compelling reason for it? How widely supported are clipboard events across browsers, and what happens in browsers that do not support the events?

**Inline styles**: I think this is a good idea. However I would like to see it manifested as a default prop, so consumers can choose to override it if they wish.

**Webpack and test page**: Is this really necessary? There's an example in the README and a link to a fiddle (admittedly, I should create a proper gh-pages branch and put that there, but it's not pressing).

I'd like to see these as discrete PRs, rather than a big set of features being added at once. The webpack/test addition I'm not even sure of, you'll have to convince me on that one :)

**Comment by WickyNilliams** [comment]
Also, can you please not change formatting of code? Stick to how it is currently formatted in terms of use of whitespace etc. Changing things like that adds noise to commits and the repo eventually ends up with inconsistent formatting. Cheers

**Comment by tnrich** [comment]
Hey Nick,

You bring up some great points. My pull request was more of a rough draft
to get my ideas out there, so I'm definitely down to modularize any of the
parts that make the cut as well as make minimal changes to the formatting.
Here are my responses to the individual units you identified:

*Webpack and test page*: This was just to let you see and test the code
quickly. No need to have it in the actual code base.

*Events*: The reason I want copy and paste event hooks is so I can have a
single place to deal with all my clipboard related needs. I'm building an
editor of sorts that needs special copy and paste functionality so it would
be nice to have a single Component that could handle both. Also, these
hooks wouldn't affect the original functionality, so if they work
correctly, I don't see the harm in having ~3 more lines of code that would
allow users to do a lot more.

I'm not sure how widely supported clipboard events are across browsers, but
React claims to unify all its events (including the "onCopy" "onPaste"
events) into synthetic events that function the same across browsers. I
don't know if there are any strange edge cases that would fail on older
browsers. Definitely something to test and make sure of.

*Inline styles*: I think making the inline styles overridable would be
fine. What exactly do you mean by "manifested as a default prop"?

A last question for you is: are you okay with having the component defined
in JSX instead of vanilla javascript? I'm unfamiliar with how to write the
component in vanilla javascript is why I ask.

Thanks for your input!

Thomas



On Jul 6, 2015 1:53 AM, "Nick Williams" <notifications@github.com> wrote:
>
> Also, can you please not change formatting of code? Stick to how it is
currently formatted in terms of use of whitespace etc. Changing things like
that adds noise to commits and the repo eventually ends up with
inconsistent formatting. Cheers
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/Z0kHbPxNAIARh17XTuN_wCR7DkiiEMMlSDmCJXMZnhh1IXFx9a_fSRbFBVZDM2QYhAeCgj55XciJzTI7stTHNfClP5ygNxAfmAXLthICgUmeCTvyioi73ysZgm_5ZuoDc3MyJNtknZSxnBzeZpR_w49U1Sbgyw=s0-d-e1-ft#https://github.com/notifications/beacon/ACmqcXIjjA86Ad-X3ijV9eV9lZ07IyAKks5oajmAgaJpZM4FSQjp.gif>

**Comment by tnrich** [comment]
Hey @WickyNilliams, 

You bring up some great points. My pull request was more of a rough draft to get my ideas out there, so I'm definitely down to modularize any of the parts that make the cut as well as rewriting those changes to make only minimal changes to the formatting. Here are my responses to the individual units you identified:

_Webpack and test page_: This was just to let you see and test the code quickly. No need to have it in the actual code base. 

_Events_: The reason I want copy and paste event hooks is so I can have a single place to deal with all my clipboard related needs. I'm building an editor of sorts that needs special copy and paste functionality so it would be nice to have a single Component that could handle both. Also, these hooks wouldn't affect the original functionality, so if they work correctly, I don't see the harm in having ~3 more lines of code that would allow users to do a lot more. 

I'm not sure how widely supported clipboard events are across browsers, but React claims to unify all its events (including the "onCopy" "onPaste" events) into synthetic events that function the same across browsers. I don't know if there are any strange edge cases that would fail on older browsers. Definitely something to test and make sure of. 

_Inline styles_: I think making the inline styles overridable would be fine. What exactly do you mean by "manifested as a default prop"?

A last question for you is: are you okay with having the component defined in JSX instead of vanilla javascript? I'm unfamiliar with how to write the component in vanilla javascript is why I ask. 

Thanks for your input!

Thomas

**Comment by tnrich** [comment]
Hmm okay so I did a bit more investigating and realized that the onCopy and onPaste event listeners can be added to any piece of the react dom, so there is no real reason to add those explicitly into your clipboard component. 

One other thing that I do think would be a cool improvement (or at least helped me with my use case) is to allow the user to pass a reference to an element they'd like to have the react-clipboard bound to:

```
<div style={{float:"right"}} 
        id="SequenceEditor" }>
   <Clipboard
            elementToListenForEventsOn={"SequenceEditor"}
            value={this.state.selectedSequenceString}
            />
</div>
```

That way, if the user has another component (such ass br-mousertrap) binding the keydown/keyup listeners to the document, the two components won't collide. Or if the user doesn't want to listen to document-wide copy events, they can specify a particular scope to act on. 

Any thoughts on that?

**Comment by tnrich** [comment]
Whoops, I take back what I said. It looks like the onCopy event can be listened to from an arbitrary div, but the onPaste event not. I think it only can be listened to on input and textarea elements. So, as there is already a textarea element within react-clipboard, it seems like it would be convenient to provide a way to hook into the onPaste event.

**Comment by WickyNilliams** [comment]
I've pushed a new version with support for `onCopy` and uses inline styles so no CSS is required anymore. `v1.2.0` on npm. I'm not going to add `onPaste` as it's outside of the remit of this component

**Pull request closed without merging**
