### PR TITLE
Add react to peerDependencies, add support for react v15, add object-…

### PR DESCRIPTION
**Pull request by sedenardi**
I've moved the dependencies to peerDependencies, as well as added support for React v15 (I've confirmed it works on 15.3.2). Since React removed object-assign from its libs, I've included the popular polyfill as a dependency.

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Sorry for the delay in response, I've been neglectful of my OSS projects recently...

Anyway, thanks for this. I'd like to avoid the object-assign dep if possible, since it's larger than the component itself.

I'm wondering if I could possibly avoid the dep if I were to switch to JSX? e.g. I could change [this line](https://github.com/WickyNilliams/react-clipboard/blob/78e3650f0bc868683175bb71035e76f68f92487e/index.js#L44) to:

```jsx
return <textarea {...this.props} readOnly onCopy={this.handleCopy} />
```

React must still have some internal implementation of Object.assign to support spreading in JSX, right?

**Comment by sedenardi** [comment]
I believe that is indeed the case. `object-assign` is a dependency of React, and judging from a cursory look at the source I can see they use it when transferring props to children (as well as propagating synthetic events).

Regardless, I believe relying on JSX whenever possible should always be considered the safest course of action since it lets React handle the underlying translation to JS objects.

**Comment by WickyNilliams** [comment]
I agree. I skipped JSX for simplicity originally, but the time has come to get a proper build setup. I'll get on it tomorrow 👍

**Comment by sedenardi** [comment]
Awesome! Thanks for following up.

**Comment by WickyNilliams** [comment]
Done, and published to npm as `v1.3.0`

**Pull request closed without merging**
